### PR TITLE
add aeroSOL to sanctum-lst-list.toml

### PR DESCRIPTION
**Pull request by gabrielhicks**

### CODE REVIEW

**Comment by gabrielhicks** [comment]
CI is failing on Fee Account assertions, I will follow up with team on telegram to work toward getting these accounts created.

**Comment by billythedummy** [comment]
could you merge master back into this branch and then i'll probably need to retrigger the CI

**Comment by gabrielhicks** [comment]
> could you merge master back into this branch and then i'll probably need to retrigger the CI
Done!

**Comment by gabrielhicks** [comment]
```
failures:
    tests::sanctum_router::verify_all_lsts_have_router_fee_token_acc_created
```
    
From my CI this is the error

**Comment by gabrielhicks** [comment]
Merged in #92

**Pull request closed without merging**
